[2025-05-03T23:29:53.038+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T23:29:53.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [queued]>
[2025-05-03T23:29:53.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [queued]>
[2025-05-03T23:29:53.269+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-03T23:29:53.308+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_pokemons> on 2025-05-02 10:00:00+00:00
[2025-05-03T23:29:53.334+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_extract', 'extract_pokemons', 'scheduled__2025-05-02T10:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_extraction.py', '--cfg-path', '/tmp/tmpt2abm7sz']
[2025-05-03T23:29:53.348+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_pokemons
[2025-05-03T23:29:53.379+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-03T23:29:53.407+0000] {standard_task_runner.py:63} INFO - Started process 256 to run task
[2025-05-03T23:29:53.654+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [running]> on host 97a6b52a1542
[2025-05-03T23:29:53.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='borginho' AIRFLOW_CTX_DAG_ID='pokemon_extract' AIRFLOW_CTX_TASK_ID='extract_pokemons' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T10:00:00+00:00'
[2025-05-03T23:29:53.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T23:36:35.843+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T23:36:35.848+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pokemon.py", line 40, in extract_pokemn
    with open(csvfile, "w", newline="", encoding="utf-8") as outfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AIRFLOW PROJETOS\\AirflowProjeto02\\data/pokemon.csv'
[2025-05-03T23:36:35.872+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemon_extract, task_id=extract_pokemons, run_id=scheduled__2025-05-02T10:00:00+00:00, execution_date=20250502T100000, start_date=20250503T232953, end_date=20250503T233635
[2025-05-03T23:36:35.923+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_pokemons ([Errno 2] No such file or directory: 'D:\\AIRFLOW PROJETOS\\AirflowProjeto02\\data/pokemon.csv'; 256)
[2025-05-03T23:36:35.982+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T23:36:36.026+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T23:36:36.036+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-03T23:48:22.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T23:48:22.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [queued]>
[2025-05-03T23:48:22.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [queued]>
[2025-05-03T23:48:22.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-03T23:48:22.399+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_pokemons> on 2025-05-02 10:00:00+00:00
[2025-05-03T23:48:22.409+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_extract', 'extract_pokemons', 'scheduled__2025-05-02T10:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_extraction.py', '--cfg-path', '/tmp/tmp1c1he8zl']
[2025-05-03T23:48:22.413+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract_pokemons
[2025-05-03T23:48:22.417+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=446) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-03T23:48:22.418+0000] {standard_task_runner.py:63} INFO - Started process 447 to run task
[2025-05-03T23:48:22.479+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_extract.extract_pokemons scheduled__2025-05-02T10:00:00+00:00 [running]> on host 97a6b52a1542
[2025-05-03T23:48:22.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='borginho' AIRFLOW_CTX_DAG_ID='pokemon_extract' AIRFLOW_CTX_TASK_ID='extract_pokemons' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T10:00:00+00:00'
[2025-05-03T23:48:22.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T23:51:53.610+0000] {logging_mixin.py:188} INFO - File deleted successfully
[2025-05-03T23:51:53.647+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-03T23:51:53.661+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T23:51:53.680+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pokemon_extract, task_id=extract_pokemons, run_id=scheduled__2025-05-02T10:00:00+00:00, execution_date=20250502T100000, start_date=20250503T234822, end_date=20250503T235153
[2025-05-03T23:51:53.856+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-03T23:51:53.900+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T23:51:53.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
